### ISSUE TITLE
Database cannot be opened.

### ISSUE THREAD

**Issue by amykayhay** [bpellin/keepassdroid#406] opened 2020-05-20 20:59 UTC
Since the last update I can no longer get logged in and have this lost access to all my very important passwords!

It seems to be inserting a lot of garbage I to the database file name.

I go in and select my database file using the file picker.  (I've tried it with the database stored on my SD card and on the physical phone in the keepass folder, but in either case the address seems to get garbled up) and then it changes the filename path to something like this "content://com.android.externalstorage.documents/document/primary%3Akeepass%2Fkeepass.kdb".  And then throws the error "  "invalid password or keyfile", but I know my password by heart, so that's not the issue.

**Comment by bpellin** [comment] 2020-08-19 01:11
Duplicate of #375.

**Closed by bpellin** 2020-08-19 01:11 UTC
