### ISSUE TITLE
Opening database fails.

### ISSUE THREAD

**Issue by PriceChild** [bpellin/keepassdroid#141] opened 2016-09-12 13:35 UTC
Error given is:

> com.keepassdroid.stream.HashedBlockInputStream.read() returned value out of range -1..255:-117

in a hovering notification.

This is a Nexus 5X with Android 7.0, build NRD90M

**Comment by monojp** [comment] 2016-09-13 07:10
This is a duplicate of #86 and should be fixed in a newer version

**Closed** 2016-11-01 01:23 UTC

**Comment by PriceChild** [comment] 2016-11-16 11:34
I'm very sorry for not confirming before but yes, it's fixed now. I think half the issue was that the freedroid builds lagged google play.
