### ISSUE TITLE
"This file type is unsupported" when opening kdbx via Google Drive Shortcut widget (used to work)

### ISSUE THREAD

**Issue by a-tuttle** [bpellin/keepassdroid#78] opened 2016-02-20 11:27 UTC
I have had this setup where I pin my kdbx file in Google Drive and create a shortcut to it using the Google Drive Shortcut Widget. This way I could just tap the shortcut from my homescreen and it would open the database in KPD.

Now tapping Google Drive shortcut to database file gives "This file type is unsupported".

Selecting the file through OIFile Manager allows me to select file from /sdcard/Android/data/com.google.android.app.docs/files/pinned_docs_files_do_not_edit/" and type password, but when tapping OK i get: "Database format not recognized.".

However, if I download the file and tap it, it opens directly in KPD and everything works fine so I could just resort to manual syncing, but I would really appreciate if you could find out if it's a Google Drive issue or not.

Phone: Samsung Galaxy Alpha (SM-G850F)
Android version: 5.0.2
KeePassDroid version: 2.0.4
Drive version: 2.3.544.17.34

**Comment by shanempope** [comment] 2016-02-25 19:18
I'm seeing the same issue. I tried clearing the cache and data on Drive like suggested in this closed issue but that's not working for me. https://github.com/bpellin/keepassdroid/issues/75 I'm guessing google broke something, but it kept suggesting i open it in 2 other apps so maybe the file association got messed up somehow.

**Comment by esmsesms** [comment] 2016-03-01 18:24
I posted a workaround at [#75](https://github.com/bpellin/keepassdroid/issues/75) while this has not been resolved.

**Comment by shanempope** [comment] 2016-03-01 19:51
I linked to it already and it did not fix it for me.

**Comment by a-tuttle** [comment] 2016-03-01 20:04
The same here, tried all the solutions mentioned in #75, but to no avail.

**Comment by grahamreeds** [comment] 2016-03-02 08:13
I started getting this today. I can confirm that the file is okay when I download.  If you download the file directly onto Linux, the mono implementation will open it.

If you download the kbdx file directly to the phone and then try to open it you see the same issue that the file is not supported.  If you email that file to a desktop email client then you can open it in your desktop keepass application.  Email it back to your mobile self and you can't open it again.

**Comment by bpellin** [comment] 2016-03-07 04:23
Duplicate of issue #75 .

**Closed by bpellin** 2016-03-07 04:23 UTC

**Comment by blakjaknz** [comment] 2022-01-04 06:04
I realise this was marked as closed-duplicate some five+ years ago but I just want to say that i'm experiencing exactly this (for kdbx files) having been using Google Drive + KeePassDroid with kdb files for the last few years without issue. So something's different. It may not be a KeePassDroid problem but it's over my head.

**Comment by grahamreeds** [comment] 2022-01-04 08:44
Yes.  I noticed this several months back.  I no longer wait to get the
error that it is no longer found and no simply open the file direct from
within Google Drive.

**Comment by Little-119** [comment] 2022-09-04 15:17
This is happening to me, and it seems to have started when I began using Linux on my PC (and thus saving my database from it and uploading it to my Google Drive from it)
