### ISSUE TITLE
Notification bar icons don't automatically disappear

### ISSUE THREAD

**Issue by hudson4351** [bpellin/keepassdroid#323] opened 2018-10-17 00:07 UTC
When using v2.3.4 of KeePassDroid, the "Select to copy username to clipboard" and "Select to copy password to clipboard" notification icons that are automatically created when I open a key in my database don’t automatically expire, even though I have my “clipboard timeout” set to 1 minute and “application timeout” set to 5 minutes.  If I re-enter the KeePassDroid app after the specified timeout period, the database is locked as expected and at that point, the notification icons automatically disappear.

**Comment by hanscappelle** [comment] 2018-11-05 14:56
After testing with release 2.3.4 on Nexus 5X I can confirm this behaviour. Could it be intentional? Just wondering because that notification is in place already when opening a key, even without ever selecting to copy a field. Also it remains active then as long as the key is open.

**Comment by hudson4351** [comment] 2018-11-05 15:33
On my S8 they used to automatically disappear after the timeout limit was reached.

**Comment by Ratio2** [comment] 2018-11-08 20:05
Samsung galaxy tab a sm-t590. After timeout clipboard cleared, but I can get password again by click in notification. No security at all. Android 8.1

**Comment by hanscappelle** [comment] 2018-12-19 09:48
Works on emulator. I did however also encounter this problem on a Nexus 5X. So I do believe it exists.

**Comment by hanscappelle** [comment] 2018-12-24 08:39
OK quick correction; it is reproducible on emulator. The notifications are hidden if you close the password entry view by going back to the entries overview for that db. If however you keep that entry view open and move app to background the notifications remain.

**Comment by bpellin** [comment] 2019-01-17 03:16
This issue affects Oreo and later. Android implemented new restrictions on services. This should be fixed in the beta version 2.4.1.

**Closed by bpellin** 2019-01-17 03:16 UTC
