### ISSUE TITLE
Locked out of Database

### ISSUE THREAD

**Issue by rayfratto** [bpellin/keepassdroid#379] opened 2019-10-31 14:08 UTC
This past week, I was locked out of my password file. I have backups dating for months, but I can't get into those as well.  I'm on a Pixel 3 and have been using the app for years and for the past few months with the same master password file.  I've also tried on my Chromebook, but nothing is working.  I doubt that it's a password issue.  Can you help?

**Comment by waveydavey692** [comment] 2020-01-20 17:43
I had keepassdroid open yesterday updating one of my passwords, I  updated android on my phone prior to opening my database (which is on Dropbox), now today I am unable to open my database!! I'm getting an invalid Password or keyfile message...even though I know my password is correct... I can open an archived database from over a year ago, but that is way out of date!!! Has the android update prior to opening the database somehow affected the password setting?? I'm not able to check on windows just yet, but did try another android device on a different version of Android and the database still will not open... Any suggestions would be welcome as I have literally hundreds of passwords stored in the database because keepassdroid has been so reliable... I've no chance of remembering all but a few!!

**Comment by ankit9j** [comment] 2020-02-12 16:48
Same problem. Been using it for years and now the DB file keeps getting corrupt every few days. I'm also using it on Pixel 3. Wonder if this is specific to Pixel 3.

It does get repaired though using KeePass 1.x for windows. The repair functionality can be found in 'Tools' → 'Repair KeePass Database File...'.

**Comment by bpellin** [comment] 2020-02-13 02:06
I've seen a lot of reports of people using the Dropbox app on android having corrupted databases recently. I've personally seen inconsistent results with the Dropbox app on android in the past, and had more success with the Dropsync app in general.

I'd recommend to try using it without Dropbox for awhile and see if you still see corruption.

**Comment by baileysh** [comment] 2020-03-10 20:45
Many Years using this, and recommending this,  and Today the App corrupted one of 2 databases.
Backup I was able to get in 2 consecutive times, and then locked out again.
-
Then it corrupted my other db.
-
Updated to latest version, restore db, and was able to log in one time to each before being locked out.
Local Storage for db on Samsung S9+
-
History this app has been used this on my Samsung S4, S7, J7, S10e, and now S9+
-
And having only Android and Linux systems,,,   Repair ??

**Comment by bwpokorny** [comment] 2020-03-14 19:16
My kdb got corrupted on 3/10/2020 as well. Fortunately, I've got backups and was also able to repair the kdb via the Windows app, as ankit9j suggested. I don't use Dropbox for syncing, so Dropbox isn't involved in my case.

I'm on a Pixel 3 as well. After repairing the kdb in Windows and transferring it back to the Pixel 3, I'm able to open, edit, and reopen the kdb without issues. So the corruption issue is intermittent.

I've used KeePassDroid for years, and this never happened to me before. The problem *may* have been caused by a recent version update of KeePassDroid on my Pixel 3, as I noticed the icon for the app changed just before the corruption happened. I'm now on version 2.5.8 of the app. Unfortunately, I don't know what version I was on previously.

I hope this helps. Other than this recent issue, KeePassDroid is fantastic.

**Comment by pronovic** [comment] 2020-03-17 15:49
I've started running into a similar corruption problem starting around 3/10/2020 as well - I noticed the problem for the first time right after the icon was updated.  I've been using this database for a lot of years now, and this marks the first time I've ever had something like this happen.  

I'm running v2.5.8 on a Pixel 2 with Android 10 (last patched on March 5).    Dropbox is not in the mix.   The database file is saved on the phone's local storage and I manually back it up every so often (it contains only a subset of passwords and the real source of record is elsewhere).  

This morning, I grabbed one of my backups, which seemed to work fine when I opened it on the phone.   I made some updates, then rebooted the phone, and got immediately locked out again.   I fixed that version of the database with the repair functionality mentioned above by @ankit9j, using the portable 1.x version for Windows.  That resolved the immediate problem, even after rebooting the phone, but I'm expecting it to happen again at some point.

Is there anything I can do to help debug this?

**Comment by jmichael2497** [comment] 2020-04-02 01:33
looks like Duplicate of #375

**Comment by bpellin** [comment] 2020-08-19 01:10
Duplicate of #375.

**Closed by bpellin** 2020-08-19 01:10 UTC

**Comment by fleskesvor** [comment] 2021-06-23 08:06
This started happening to me last week. I went through several backups to see which worked on my PC (Pop!_OS (Ubuntu 20.04)), and it seemed only the ones that I hadn't tried to open in KeePassDroid still worked. After that, I tried to open some of those confirmed to be working database-files in KeePassDroid, and they fail with the same message.
