### ISSUE TITLE
.kdb database corruption when saved

### ISSUE THREAD

**Issue by K3TZ** [bpellin/keepassdroid#375] opened 2019-10-04 15:43 UTC
I've been using KeePass Android for many years without a hitch. I trusted it so much that I haven't made a backup of my database in years ( I know, my bad).

I have a Pixel 2 and recently got upgraded to Android 10.

I updated a password in my database since then and now I am locked out of it.

I am running 2.4.1 and I have tried setting the Key encryption rounds before corruption value to 6000, 50000, and 100000 and was unsuccessful.

I installed KeePass on my windows PC and tried to open my database there. It says I have an old database (.kbd 1x) and I followed the instructions to import again without success.

I know my password and I do not use a key file.

Any chance I can get this resolved?  I have a ton of passwords that I don't remember.

Thanks!

**Comment by andymnc** [comment] 2019-10-17 19:59
same problem here.
google pixel 2xl, android 10, keppassdroid and an old .kdb 
after deleting a key, it says wrong pw. but it's the same.
maybe if there was a way to import the kdb and export it in kdb2 ... 
but as per now, i can't delete any key from my db or i will never enter anymore

**Comment by waveydavey692** [comment] 2020-01-20 17:42
Same problem here... I had keepassdroid open yesterday updating one of my passwords, I  updated android on my phone prior to opening my database (which is on Dropbox), now today I am unable to open my database!! I'm getting an invalid Password or keyfile message...even though I know my password is correct... I can open an archived database from over a year ago, but that is way out of date!!! Has the android update prior to opening the database somehow affected the password setting?? I'm not able to check on windows just yet, but did try another android device on a different version of Android and the database still will not open... Any suggestions would be welcome as I have literally hundreds of passwords stored in the database because keepassdroid has been so reliable... I've no chance of remembering all but a few!!

**Comment by brimstoned** [comment] 2020-01-23 15:12
Same thing happened to me.  Pixel 2XL, Android 10 (just installed January 2020 Security update a few days), KeePassDroid 2.4.1.  I added an entry to my database and saved.  When I tried to open it I get "Invalid password or keyfile".  When I try to open on deskop, I get the same error.

**Comment by brimstoned** [comment] 2020-01-27 14:56
I wanted to update this thread on my progress.  I used the official Keepass desktop app's "Repair Database" feature to fix my corrupted database.  The repair function does not check the integrity of the data and could introduce errors, so all credentials should be checked.  Luckily, I had a one month old backup and compared both the backup and the repaired version and everything was correct.  The repaired version even had the new entry that was added when KeePassDroid (or Android 10) corrupted the database.

https://keepass.info/help/base/repair.html

Notes on comparing:  In the desktop app, you have to enable unsafe operations.  Then export both database to either an xml file or text file (I did XML).  Then use a text comparison application to compare (I used WinMerge).  I would not do this on a plain-text HDD or flash drive since all of your passwords will be written out, and could linger after deleting the text files.  I recommend you should should export to a an encrypted file system (Veracrypt can be used to create a temporary one) and securely erase it afterwards.  That might be overkill.  Another option is you could just securely delete the text files on the HDD.

I hope this helps.

**Comment by ankit9j** [comment] 2020-02-12 16:56
+1 the DB file keeps getting corrupt every other day on Pixel 3 and needs to be repaired using https://keepass.info/help/base/repair.html on Windows

**Comment by jmichael2497** [comment] 2020-04-02 01:14
okay, so this *is* still an issue with databases in KeePassDroid.

i saw in another thread folks saying they had the same problem even after switching to KeePass2Android but have you tried that lately? it seems to expose way more options.

and what about KeePassDX as well? since all 3 seem to share code, might be more visual variety rather than behavior change, but at least has a few more options, though not as many as KP2A?

would be nice if there was a teamup between all 3 devs to join forces.

**Comment by rayfratto** [comment] 2020-04-02 11:25
I've switched to Keepass2Android after my post last year and haven't looked back.  I'm way happier with it.

**Comment by smvicente** [comment] 2020-05-06 16:25
I'm on the same boat. Database corruption with a Pixel 2XL, but in my case I've been able to narrow it down to when I remove an entry, not when modifying or creating a new one.

**Comment by bpellin** [comment] 2020-08-19 01:22
I have been trying to reproduce this issue without success. I have tried repeating the steps listed in various versions of this issue, but I have never seen the data corruption. I need help narrowing down what tho involved factors are.

If you experience this issue can you answer the following questions:
1. What version of KeePassDroid are you using (check the About pop-up in the app)?
2. Are you using a .kdb or .kdbx database?
3. What other versions of KeePass do you use to edit your database (e.g. KeePass 1.38 on Windows, keepassx 0.4.4 on Linux)?
4. How do you open your database in KeePassDroid? Do you open another application and click on your keepass database? Do you open KeePassDroid and click on the folder icon and use another application to browse to the file?
5. What does the file URL look like for your database in KeePassDroid (e.g. file://storage/emulated/0/keepass.kdb, content://com.adroid.externalstorage.documents/...)?
6. Do you use any thing to automatically sync your database to your phone and other devices?
7. What was the last update you made to your database before seeing corruption (e.g adding an entry, removing an entry, updating an entry)?

**Comment by pronovic** [comment] 2020-08-19 02:23
@bpellin, I had repeated problems in early March, which have not been reoccurred since my last comment over in #379.  I don't think I'm doing anything different now than I was then.  

- What version of KeePassDroid are you using (check the About pop-up in the app)?

I have a Pixel 2 running Android 10, and I use KeePassDroid v2.5.12

- Are you using a .kdb or .kdbx database?

.kdb

- What other versions of KeePass do you use to edit your database (e.g. KeePass 1.38 on Windows, keepassx 0.4.4 on Linux)?

None

- How do you open your database in KeePassDroid? Do you open another application and click on your keepass database? Do you open KeePassDroid and click on the folder icon and use another application to browse to the file?

I open KeePassDroid and open my default database.  I only have the one, so after finding it the first time I've never needed to change it.

- What does the file URL look like for your database in KeePassDroid (e.g. file://storage/emulated/0/keepass.kdb, content://com.adroid.externalstorage.documents/...)?

I see this on the first screen of the app: `content://com.android.externalstorage.docu...`  I'm not sure how to get the complete URL?

- Do you use any thing to automatically sync your database to your phone and other devices?

No, I do this manually.  The phone only stores a frequently-used subset of my passwords, which don't change very often.

- What was the last update you made to your database before seeing corruption (e.g adding an entry, removing an entry, updating an entry)?

I am not certain, but I am fairly sure that I was editing existing entries rather than adding new ones.

**Comment by smvicente** [comment] 2020-08-25 17:18
1. What version of KeePassDroid are you using (check the About pop-up in the app)?
2.5.12
2. Are you using a .kdb or .kdbx database?
.kdb
3. What other versions of KeePass do you use to edit your database (e.g. KeePass 1.38 on Windows, keepassx 0.4.4 on Linux)?
KeePassX 0.4.4 on Linux
4. How do you open your database in KeePassDroid? Do you open another application and click on your keepass database? Do you open KeePassDroid and click on the folder icon and use another application to browse to the file?
I open KeePassDroid and open my default database.
5. What does the file URL look like for your database in KeePassDroid (e.g. file://storage/emulated/0/keepass.kdb, content://com.adroid.externalstorage.documents/...)?
content://com...
6. Do you use any thing to automatically sync your database to your phone and other devices?
FolderSync. But I don't think it is related.
7. What was the last update you made to your database before seeing corruption (e.g adding an entry, removing an entry, updating an entry)?
Removing an entry or part of an entry. Basically always the total size of the DB is reduced. No problems adding.

**Comment by bpellin** [comment] 2020-08-27 03:10
Thanks @smvicente. The point about lowering the size of the database was key.

On certain versions of android with certain content providers, it doesn't trim the size of the database when it is reduced. This caused the corruption.

This will be fixed in v2.5.13.

**Closed by bpellin** 2020-08-27 03:10 UTC

**Comment by smvicente** [comment] 2020-08-27 10:45
Thanks!!

**Comment by J-Jamet** [comment] 2020-08-31 15:13
Thank you! :)
