### ISSUE TITLE
KeePassDroid doesnt open database - says Master password is wrong (its not)

### ISSUE THREAD

**Issue by JoanaRibeiroDuarte** [bpellin/keepassdroid#420] opened 2020-08-04 13:31 UTC
Changed description in one item inside database in KeePassDroid  - it shut down and doesn't open. Keeps saying Master password is incorrect.

I opened a backup of same database - its out of date, but has some passwords - to see if I was making a mistake with inputting the Master password. It opened with Master password, and this  Master password is exactly the same as the one I have in the corrupted DB.

KeePassDroid version is 2.5.12, mobile device is Samsung A6, Model SM-A600FN.

How do I recover my corrupted database - as it has passwords I dont have on the backup - and will this happen everytime I open the database in KeePassDroid?

**Comment by costantino22** [comment] 2020-08-09 09:16
Had some problem today. Yesterday I updated keepassdroid from PlayStore. This morning I opened the database, updated 1 password for one of my accounts also registering my fingerprint to open keepassdroid.
Now I am unable to open it. 
I had an old backup of db and it opens with the password.

**Comment by costantino22** [comment] 2020-08-09 09:21
It just happened again. I updated one entry in keepassdroid and now I am unable to open again.

**Comment by costantino22** [comment] 2020-08-09 11:38
The issue happens if you access the db through the path storage/emulated/0/keepass/kpd.kbd or if you use a file manager and then on the db file, you tap and open with... After having accessed the first time with the password and modified an entry, the next time the password will not be recognized.

I accessed the db writing manually the path sdcard/keepass/kpd.kbd and now it works fine.

The issue I have now is that I cannot access any longer the last updated db.

**Comment by costantino22** [comment] 2020-08-17 08:56
Downloaded the DB on PC, started an old version of KeePass (1.24?), in tag "Tools" I succeeded to repair with old password.

**Comment by bpellin** [comment] 2020-08-19 01:10
Duplicate of #375

**Closed by bpellin** 2020-08-19 01:10 UTC
