### ISSUE TITLE
Unable to access Version 2.5.12

### ISSUE THREAD

**Issue by M300PTY** [bpellin/keepassdroid#416] opened 2020-07-15 21:09 UTC
My KeePassDroid version 2.5.12 on my Galaxy Note 9 worked well on 14th July.  Today it is not allowing me access.  Not sure if there was an update since last used.  I have backups, but I cannot access them.  Would you have any suggestions for accessing my latest backups?  Or is there a way to reset the password to access that version 2.5.12 of the kdb?
Thanks

**Comment by bpellin** [comment] 2020-08-19 01:10
Duplicate of #375.

**Closed by bpellin** 2020-08-19 01:10 UTC
